ManageTask/urls.py
from django.urls import path
from . import views

app_name = 'ManageTask'
urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/task-lists/<int:list_name>', views.task_list, name='task_list'),
    path('dashboard/task-lists/<str:list_name>/<int:task_id>/',views.specific_task, name='specific_task'),
    path('mark-as-done/<int:task_id>/', views.mark_as_done, name='mark_as_done'),
    path('update-task/<int:task_id>/', views.update_task, name='update_task'),
    path('dashboard/task-lists/<str:list_name>/add-task/', views.add_task, name='add_task'),
    path('delete-task/<int:task_id>/', views.delete_task, name='delete_task'),


]

ToDoApplication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ManageTask/', include('ManageTask.urls')),
]

ManageTask/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


class Person(User):
    gender_choice = [('M', 'Male'),
                     ('F', 'Female'),
                     ]
    gender = models.CharField(verbose_name='Gender', max_length=6, choices=gender_choice, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'password1', 'password2']

    def __str__(self):
        """
        Message: Show person name as default
        Parameters:
            self:
        Returns:
            name (str): Return person name
                """
        return '{} {}'.format(self.first_name.title(), self.last_name.title())


class TaskList(models.Model):
    task_list_title = models.CharField(max_length=50, blank=False)
    task_list_description = models.TextField()
    owner = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __str__(self):
        """
        Message: Show task_list title as default
        Parameters:
            self:
        Returns:
            task__list_title (str): Return task_list title
        """
        return self.task_list_title


class Task(models.Model):
    task_title = models.CharField(max_length=100, blank=False)
    task_description = models.TextField()
    start_date = models.DateTimeField(default=datetime.now())
    completed_date = models.DateTimeField(blank=True, null=True, default=None)
    is_complete = models.BooleanField(default=False)
    task_list = models.ForeignKey(TaskList, on_delete=models.CASCADE)

    def __str__(self):
        """
        Message: Show task title as default
        Parameters:
            self:
        Returns:
            task_title (str): Return task title
        """
        return self.task_title

ManageTask/forms.py
from django.forms import ModelForm, Form
from django import forms
from .models import Person, Task


class PersonForm(ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        # Making fields required
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

    class Meta:
        model = Person
        # fields = '__all__'
        fields = ['first_name', 'last_name', 'username', 'password', 'email', 'gender']
        exclude = ('is_staff', 'is_active', 'is_superuser', 'groups', 'user_permissions', 'date_joined', 'last_login')


class LoginForm(forms.Form):

    # def __init__(self, *args, **kwargs):
    #     super(Form, self).__init__(*args, **kwargs)
    #     # Making fields required
    #     self.fields['username'].required = True
    #     self.fields['password'].required = True

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('task_title', 'task_description')

ManageTask/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import PersonForm, LoginForm, TaskForm
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseForbidden
from .models import Person, TaskList, Task
from datetime import datetime


def register(request):
    if request.method == 'POST':
        p1 = PersonForm(request.POST)
        if p1.is_valid():
            first_name = p1.cleaned_data.get("first_name")
            last_name = p1.cleaned_data.get("last_name")
            username = p1.cleaned_data.get("username")
            password = p1.cleaned_data.get("password")

            user = Person(first_name=first_name, last_name=last_name, username=username)
            user.set_password(password)
            user.is_staff = True
            user.save()
            return HttpResponse("Registered successfully")
        else:
            context = {'register_form': p1}
            return render(request, template_name='ManageTask/register.html', context=context)
    else:
        form = PersonForm()
        context = {'register_form': form}
        return render(request, template_name='ManageTask/register.html', context=context)

# ################################################################################################### #


def main_page(request):
    return render(request=request, template_name='ManageTask/main_page.html', context={})


# ################################################################################################### #


def login_user(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                request.session['current_user'] = username
                login(request, user)
                # Redirect to a success page.
                return HttpResponseRedirect('/ManageTask/dashboard/')
            else:
                return HttpResponse('User with provided CREDENTIALS not found. '
                                    'Please check your username and password. ')

        else:
            return render(request=request, template_name='ManageTask/login.html',
                          context={'login_form': login_form})
    else:
        current_user = request.user
        try:
            if str(request.session['current_user']) == str(current_user):
                return HttpResponseRedirect('/ManageTask/dashboard/')
        except KeyError:
            login_form = LoginForm()
            return render(request=request, template_name='ManageTask/login.html',
                          context={'login_form': login_form})


# ################################################################################################### #


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/ManageTask/')


# ################################################################################################### #


def get_user_list(username):
    user = Person.objects.get(username=username)
    user_list = TaskList.objects.filter(owner=user.user_ptr_id)
    return user_list


# ################################################################################################### #


def dashboard(request):
    try:

        user = Person.objects.get(username=request.session['current_user'])
        task_list = get_user_list(user.username)
        tasks = {}
        for lists in task_list:
            task = Task.objects.filter(task_list=lists)
            if task is not None:
                tasks[task] = lists
        fullname = user.first_name + ' ' + user.last_name
        fullname = fullname.title()
        tasks_dict = {}
        for ind, tl in enumerate(task_list):
            tasks_dict[ind] = Task.objects.filter(task_list=tl)
        data = {
            'user': fullname,
            'task_list': task_list,
            'tasks': tasks_dict
        }
        return render(request=request, template_name='ManageTask/dashboard.html',
                      context={'data': data})
    except KeyError:
        return HttpResponseRedirect('/ManageTask/login/')
    except Person.DoesNotExist:
        raise Http404(f'No Person Exist with username: {request.user}')


# ################################################################################################### #


def task_list(request, list_name):
    if not validate_request(request):
        return HttpResponseForbidden()
    else:
        list_of_task = TaskList.objects.filter(id=list_name)
        name_of_list = list_of_task[0]
        tasks = Task.objects.filter(task_list=list_name)
        completed_tasks = tasks.filter(is_complete=True)
        incomplete_tasks = tasks.filter(is_complete=False)
        data = {'name_of_list': name_of_list,
                'tasks': tasks,
                'id': name_of_list.id,
                'completed_tasks': completed_tasks,
                'incomplete_tasks': incomplete_tasks
                }
        return render(request=request, template_name='ManageTask/task_list.html', context=data)


# ################################################################################################### #


def specific_task(request, list_name, task_id):
    if not validate_request(request):
        return HttpResponseForbidden()
    else:
        task = Task.objects.filter(id=task_id)
        task = task[0]
        current_address = request.get_full_path()
        context = {'task_title': task.task_title,
                   'task_id': task.id,
                   'task_description': task.task_description,
                   'start_date': task.start_date,
                   'is_complete': task.is_complete,
                   'completed_date': task.completed_date,
                   'address': current_address

                   }
        return render(request=request, template_name='ManageTask/specific_task.html', context=context)


# ################################################################################################### #


def mark_as_done(request, task_id):
    if not validate_request(request):
        return HttpResponseForbidden()
    else:
        my_task = Task.objects.filter(pk=task_id)
        my_task = my_task[0]
        my_task.is_complete = True
        my_task.completed_date = datetime.now()
        my_task.save()
        current_address = request.get_full_path()
        print(current_address)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# ################################################################################################### #


def update_task(request, task_id):
    if validate_request(request):
        task = Task.objects.filter(pk=task_id)
        task_form = TaskForm()
        return render(request=request, template_name=update_task,context={})
    else:
        return HttpResponse('Updating')


# ################################################################################################### #


def delete_task(request, task_id):
    if validate_request(request):
        task = Task.objects.filter(pk=task_id)
        task.delete()
        return HttpResponseRedirect('/ManageTask/dashboard/')
    else:
        return HttpResponseForbidden()


# ################################################################################################### #


def add_task(request, list_name):
    if validate_request(request):
        if request.method == 'POST':
            task_form = TaskForm(request.POST)
            if task_form.is_valid():
                task_title = task_form.cleaned_data.get('task_title')
                task_description = task_form.cleaned_data.get('task_description')
                task_list_id = task_form.cleaned_data.get('task_list')
                current_time = datetime.now()
                print(current_time)

                required_list = TaskList.objects.filter(pk=list_name)
                required_list = required_list[0]

                task = Task(task_title=task_title, task_description=task_description,
                            task_list=required_list, is_complete=False, start_date=current_time)
                task.save()
                return HttpResponse('Task inserted.')
            else:
                return render(request=request, template_name='ManageTask/add_task.html',
                              context={'form': task_form})
        else:
            task_form = TaskForm()
            return render(request=request, template_name='ManageTask/add_task.html',
                          context={'form': task_form})
    else:
        return HttpResponseForbidden()


# ################################################################################################### #


def validate_request(request):
    try:
        user = Person.objects.get(username=request.user)
        return True
    except Person.DoesNotExist:
        return False


# ################################################################################################### #

ManageTask/templates/ManageTask/add_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Task</title>
</head>
<body>

    <h1>Add Task</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{form}}
        </table>
        <button class="btn btn-primary" type="submit">Add Task</button>

    </form>



</body>
</html>

ManageTask/templates/ManageTask/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
</head>
<body>
    <h1 style="color:DarkSlateGray;">Welcome {{data.user}}
    <a href="{% url 'ManageTask:logout' %}">
        <button type="submit">
        Logout
        </button>
    </a>
    </h1>
    <h2 style="color:Teal;">You have the Following Lists Available</h2>
    {% for specific_list in data.task_list %}
        <a href="{% url 'ManageTask:task_list' specific_list.id%}"> <h3 style="color:BlueViolet;">{{specific_list}}</h3></a>
<!--        <ul>-->
<!--            {% for task in data.tasks.values %}-->
<!--                <li>{{task}}</li>-->

<!--            {% endfor %}-->
        </ul>

    {% endfor %}
</body>
</html>

ManageTask/templates/ManageTask/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
</style>
</head>
<body>
  <h1>Login</h1>
  <table>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{login_form}}
        </table>
        <input type="submit" name="login" value="Log In">
    </form>
  </table>

</body>
</html>

ManageTask/templates/ManageTask/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TMS</title>
</head>
<body>
        <h1>Welcome to Task Management System</h1>
        <h2><a href="{% url 'ManageTask:register' %}">Register</a></h2>
        <h2><a href="{% url 'ManageTask:login' %}">Login</a></h2>
</body>
</html>

ManageTask/templates/ManageTask/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>

	<div>
		<h1>Registration Form</h1>
		<form method="POST">
			{% csrf_token %}
			<table >
				{{ register_form }}
			</table>
			<button class="btn btn-primary" type="submit">Register</button>
		</form>
	</div>

</body>
</html>

ManageTask/templates/ManageTask/specific_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{task_title}}</title>
    <style>
        table, th, td {
        width:70%;
        border: 1px solid black;
        }
</style>
</head>
<body>
    <h1>{{task_title}}</h1>
    <h2>Details</h2>

    <table style="table-layout:fixed;">
        <tr>
            <th style="width:150%">Task_Description</th>
            <th style="width:40%">Start Date</th>
            <th style="width:30%">Is Complete</th>
            <th style="width:40%">Completed_Date</th>
        </tr>
          <tr>
              <td>{{task_description}}</td>
              <td>{{start_date}}</td>
              <td>{{is_complete}}</td>
              <td>{{completed_date}}</td>
        </tr>
    </table>
    <br>
    <a href="{% url 'ManageTask:update_task' task_id %}"><input type="submit" value="Update"></a>

    <br>
    <br>
    {% if is_complete %}
        <a href="{% url 'ManageTask:mark_as_done' task_id %}">
            <button type="submit" disabled>
                Mark As Done
            </button>
        </a>
    {% else %}
        <a href="{% url 'ManageTask:mark_as_done' task_id %}">
            <button type="submit">
                Mark As Done
            </button>
        </a>
    {% endif %}
    <br>
    <br>
    <a href="{% url 'ManageTask:delete_task' task_id %}"><input type="submit" value="Delete This Task"></a>


</body>
</html>

ManageTask/templates/ManageTask/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TaskLists</title>
</head>
<body>
    <h1 style="color:DarkSlateGray;">List <span style="color:red;">{{name_of_list}}</span> Contains Following Tasks </h1>

    <h2>Tasks in progress</h2>
    <h3>
    {% for task in incomplete_tasks%}
    <li><a href="{{id}}/{{task.id}}/"> {{ task }}</a></li>
    {% endfor %}
    </h3>
    <br>
    <br>
    <a href="{% url 'ManageTask:add_task' id %}">
        <button type="submit">
        Add Task
        </button>
    </a>
    <h2>Completed Tasks</h2>
        <h3>
            {% for task in completed_tasks %}
                <li><a href="{{id}}/{{task.id}}/"> {{ task }}</a></li>
            {% endfor %}
        </h3>

</body>
</html>

ManageTask/templates/ManageTask/update_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Task</title>
</head>
<body>

</body>
</html>